var group__mx__api =
[
    [ "ac_owns_path()", "group__mx__ac__owns__path.html", "group__mx__ac__owns__path" ],
    [ "ac_add()", "group__mx__ac__add.html", "group__mx__ac__add" ],
    [ "mbox_open()", "group__mx__mbox__open.html", "group__mx__mbox__open" ],
    [ "mbox_open_append()", "group__mx__mbox__open__append.html", "group__mx__mbox__open__append" ],
    [ "mbox_check()", "group__mx__mbox__check.html", "group__mx__mbox__check" ],
    [ "mbox_check_stats()", "group__mx__mbox__check__stats.html", "group__mx__mbox__check__stats" ],
    [ "mbox_sync()", "group__mx__mbox__sync.html", "group__mx__mbox__sync" ],
    [ "mbox_close()", "group__mx__mbox__close.html", "group__mx__mbox__close" ],
    [ "msg_open()", "group__mx__msg__open.html", "group__mx__msg__open" ],
    [ "msg_open_new()", "group__mx__msg__open__new.html", "group__mx__msg__open__new" ],
    [ "msg_commit()", "group__mx__msg__commit.html", "group__mx__msg__commit" ],
    [ "msg_close()", "group__mx__msg__close.html", "group__mx__msg__close" ],
    [ "msg_padding_size()", "group__mx__msg__padding__size.html", "group__mx__msg__padding__size" ],
    [ "msg_save_hcache()", "group__mx__msg__save__hcache.html", "group__mx__msg__save__hcache" ],
    [ "tags_edit()", "group__mx__tags__edit.html", "group__mx__tags__edit" ],
    [ "tags_commit()", "group__mx__tags__commit.html", "group__mx__tags__commit" ],
    [ "path_probe()", "group__mx__path__probe.html", "group__mx__path__probe" ],
    [ "path_canon()", "group__mx__path__canon.html", "group__mx__path__canon" ],
    [ "path_pretty()", "group__mx__path__pretty.html", "group__mx__path__pretty" ],
    [ "path_parent()", "group__mx__path__parent.html", "group__mx__path__parent" ],
    [ "path_is_empty()", "group__mx__path__is__empty.html", "group__mx__path__is__empty" ],
    [ "MxCompOps", "group__mx__api.html#ga69f737b0581952c0ef57f37af78ac6c7", null ],
    [ "MxImapOps", "group__mx__api.html#ga9cd881485b601b78cae25ade04b475c8", null ],
    [ "MxMaildirOps", "group__mx__api.html#ga0748343fa768080ad12f35154d7dfbde", null ],
    [ "MxMhOps", "group__mx__api.html#ga1c6613efa24f50ed6d0c077738937838", null ],
    [ "MxMboxOps", "group__mx__api.html#gaad6c863fc1a5e9df89b83c04c78ebadb", null ],
    [ "MxMmdfOps", "group__mx__api.html#ga6f5aa20334c61002a91427dec14cc4e3", null ],
    [ "MxNntpOps", "group__mx__api.html#ga94647e4d7fc43a4cbaa0f477545f478d", null ],
    [ "MxNotmuchOps", "group__mx__api.html#gaeb8eaded43f46d1709e8174fccbe5004", null ],
    [ "MxPopOps", "group__mx__api.html#gaec53cbb4297fe9b475784600a3957dc7", null ]
];